### ISSUE TITLE
Configuration file does not exist

### ISSUE THREAD

**Issue by pmnlla** [jpdunn/Discord-Bot-Template#2]
I was looking through the code of the config file loader to figure out what i was doing wrong. Turns out i needed a JSON file that was not in there.
I do not know how i should format the JSON file and where it is in order for it to be readable.

**Comment by pmnlla** [comment]
Also, a large part of the code was errors due to an outdated version of Discord.Net

**Comment by akacdev** [comment]
It should be located in _/bin/debug/netcoreapp2.1/resources/config.json_
I've been using a code from this to launch my bot, but today I started to have issues with launching the bot, this is the step where it fails. It doesn't throw any errors, it just crashes.

**Comment by akacdev** [comment]
I'm sorry, this is for an other bot.
